### ISSUE TITLE
Hi! 我有个关于recharts在flexdashboard无法显示图的问题想问问你！

### ISSUE THREAD

**Issue by yt2639** [cailuzhaixing/r-#1]
您好！我在https://github.com/cosname/recharts/issues/57 看到了你的回答。在Rmarkdown的flexdashboard框架里，如何才能render出图哇？我的rmd点击Run Document之后就是空白的，不出图。可不可以看一看你是怎么写的哇？谢谢！！

**Comment by cailuzhaixing** [comment]
我一向是用knit to html
